#kubectl run n1 --image=nginx --port=80
#kubectl expose pod n1 --port=80 --target-port=80 --name=n1s --type=LoadBalancer
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Pod
metadata:
  name: n1
  labels:
    env: dev
    app: nginx
  namespace: dev
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: n1s
  namespace: dev
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
